# BUTTON MAPPING OPTIONS ( DON'T CHANGE )
32B_BUTTON:
  BUTTON_1:         0
  BUTTON_2:         1
  BUTTON_3:         2
  BUTTON_4:         3
  BUTTON_5:         4
  BUTTON_6:         5
  BUTTON_7:         6
  BUTTON_8:         7
  BUTTON_9:         8
  BUTTON_10:        9
  BUTTON_11:        10
  BUTTON_12:        11
  BUTTON_13:        12
  BUTTON_14:        13
  BUTTON_15:        14
  BUTTON_16:        15
  BUTTON_17:        16
  BUTTON_18:        17
  BUTTON_19:        18
  BUTTON_20:        19
  BUTTON_21:        20
  BUTTON_22:        21
  BUTTON_23:        22
  BUTTON_24:        23
  BUTTON_25:        24
  BUTTON_26:        25
  BUTTON_27:        26
  BUTTON_28:        27
  BUTTON_29:        28
  BUTTON_30:        29
  BUTTON_31:        30
  BUTTON_32:        31

#EDIT DEBUG CONFIGURATION 

MAP_DEBUG:          False

#EDIT JOYSTICK CONFIGURATION 

MAP_XY:
  INPUT_MIN:        -16
  INPUT_MAX:         16
  INPUT_DEADZONE:    1
  OUTPUT_MIN:       -127
  OUTPUT_MAX:        127
  OPERATION_MODE:    0  
  REACTION_TIME:     10 

#EDIT BUTTON MAPPING 
  
MAP_MOUSE:
  BTN_LEFT:          BUTTON_1
  BTN_RIGHT:         BUTTON_2
  BTN_MIDDLE:        BUTTON_3
  BTN_SIDE:          BUTTON_4
  BTN_EXTRA:         BUTTON_5
  
MAP_KEYBOARD:
  KEY_A:             BUTTON_1
  KEY_B:             BUTTON_2
  KEY_X:             BUTTON_3
  KEY_Y:             BUTTON_4
  KEY_1:             BUTTON_1
  KEY_2:             BUTTON_2
  KEY_3:             BUTTON_3
  KEY_4:             BUTTON_4
  KEY_5:             BUTTON_5
  KEY_6:             BUTTON_6
  KEY_7:             BUTTON_7
  KEY_8:             BUTTON_8
  KEY_UP: 
   X: 0
   Y: -127
  KEY_RIGHT: 
   X: 127
   Y: 0
  KEY_DOWN: 
   X: 0
   Y: 127
  KEY_LEFT: 
   X: -127
   Y: 0
  
MAP_OTHERS:
  REL_WHEEL:          BUTTON_16